### ISSUE TITLE
Question: What happened to the chatter option?

### ISSUE THREAD

**Issue by CrazyCSIW6** [ineedbots/iw4x_bot_warfare#3]
It seems to be all but gone from the mod now. Why was it removed? I liked it.
In my opinion, it was one of Bot Warfare's biggest selling points, and it was the reason why I installed the mod to begin with.
It would be great if it could be re-added because it was hilarious watching 5 bots hackusate each other.
If it was removed because people didn't like it, they could've just turned it off. Not that hard to do.
Many thanks from CrazyCSIW6

**Comment by ineedbots** [comment]
It didnt make it to this release because the focus of this version was on the bot's gameplay and stability. Now that is finished, I will add some chat events firing, and make a base chatter script with the original dialog, it's planned to be modular. It should be easy for people to add their own dialog.

**Comment by CrazyCSIW6** [comment]
> It should be easy for people to add their own dialog.

Yay, custom hackusations!
Seriously though, that feature sounds promising. I felt like there weren't enough lines for tactical nuke reactions, so it's great to see that problem will be resolved with custom dialog support.
Thanks for clearing that up. Appreciate it.

**Comment by Snickers-Projects** [comment]
> 
> 
> It didnt make it to this release because the focus of this version was on the bot's gameplay and stability. Now that is finished, I will add some chat events firing, and make a base chatter script with the original dialog, it's planned to be modular. It should be easy for people to add their own dialog.

Would be a cool feature indeed. But man, I can see why it got sidelined for a bit for bot gameplay and such. Had a LAN recently with some extra bots to pad out the server and they were amazing, they really do make you forget they're bots for the most part.

It's the little things like how they jump when you surprise them, (don't know if that's actually coded in, but they do it now and then and it really makes them feel "real") or the way they will just aim at your feet with a rocket launcher when there's a few people in a knife fight and they blow themselves and everyone in the group way (Again, not sure if intentional, but man it was fun). 

They are hyper aggressive against kill streaks, but that actually balances things out at a lan quite well. Anyway, just wanted to let you know you made our night an awesome one.

**Comment by ineedbots** [comment]
![image](https://user-images.githubusercontent.com/751729/163728977-6d72593b-e104-4b19-bfb0-68264203ffb1.png)
working on it

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4x_bot_warfare/blob/master/userraw/maps/mp/bots/_bot_chat.gsc
