### ISSUE TITLE
11+ bots lag my game.

### ISSUE THREAD

**Issue by krevic** [ineedbots/iw4x_bot_warfare#49]
I use bot warfare on IW5 and it runs without any problems, but on IW4x it begins to stutter when I add more than 11 bots.

**Comment by DJCPT** [comment]
I'm having the same issue. Whenever I play with around 7 or more bots in a private game of iw4x, I get a weird jittery camera on my 170hz display even though my fps is high (200+). It happens very slightly with like 2-6 bots, but once I get to 7 bots it becomes noticeable easily and at 11 bots (6v6) the game gets extremely jittery as if it's capping my game to 60fps even though the counter says I'm getting over 200. May be a limitation with the engine sadly but am hoping that it is fixable because I LOVE this mod. Literally gives me a perfect way to experience pure MW2 with no modifications or weird guns and stuff.

**Comment by Acelya-9028** [comment]
Same :s

**Comment by LevelChecker** [comment]
The bots are very CPU intensive this is expected, try not to run more than a 6v6 game, I have not had issues with lag with this amount, also, run the bots on a dedicated server instead, this will remove almost all/all lag. By running the game and server in the same instanced lobby, a lot of things are being processed at the same time resulting in immense lag spikes

**Comment by ineedbots** [comment]
dupe #45
